### ISSUE TITLE
后端运行报错

### ISSUE THREAD

**Issue by songliqiang520** [baizunxian/zerorunner#68]
![image](https://github.com/baizunxian/zerorunner/assets/34465699/2d56ccee-b4c3-4b9b-b537-16b00afe8083)

**Comment by songliqiang520** [comment]
大佬给看看呗

**Comment by baizunxian** [comment]
> 大佬给看看呗
项目后端目录下新建.env文件并且把报错哦的的配置写入，重新运行项目
